/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Tet7IvBdpNy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Cabin } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

cabin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function About() {
  return (
    <div key="1" className="flex flex-col items-center justify-center px-4 py-12 sm:px-6 lg:flex">
      <div className="space-y-4">
        <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">About Us</div>
        <div className="space-y-4">
          <h1 className="text-3xl font-bold xl:text-4xl/relaxed">About Resmue Builder</h1>
          <p className="text-gray-500 dark:text-gray-400">
            We believe that everyone should have access to tools that help them put their best foot forward in the job
            market. Our mission is to empower job seekers by providing them with the resources they need to create
            professional, polished resumes that stand out to employers. We understand that the job application process
            can be daunting, which is why we are committed to making it easier for candidates to showcase their skills
            and experience. At Remue Builder, we are driven by our passion for helping others succeed.
          </p>
        </div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Our Values</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Accessibility</li>
            <li>Innovation</li>
            <li>Empowerment</li>
            <li>Inclusivity</li>
            <li>Excellence</li>
          </ul>
        </div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold ">
            The Team
            <div className=" flex-cols">
            <div className="flex items-center space-x-2 text-lg">
              <span>Jenin Joseph</span>
              <GithubIcon className="h-5 w-5" />
            </div>
            <div className="flex items-center space-x-2 text-lg">
              <span>Alan K Anil</span>
              <GithubIcon className="h-5 w-5" />
            </div>
            <div className="flex items-center space-x-2 text-lg">
              <span>Archana OS</span>
              <GithubIcon className="h-5 w-5" />
            </div>
            </div>
          </h2>
          <div>
            <div className="mx-auto grid max-w-3xl items-start gap-4 px-4 lg:px-0" />
          </div>
        </div>
      </div>
      <div className="mx-auto grid max-w-3xl items-start gap-4 px-4 lg:px-0" />
    </div>
  )
}

function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}
