/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QV9dJ6zcsZf
 */
import Link from 'next/link';
import { JSX, SVGProps } from 'react';
import { Button } from './ui/button';

export function Hero() {
  return (
    <>
      <section className="flex items-center justify-center w-full min-h-screen py-12 gap-4 px-4 text-center md:px-6 lg:py-24 xl:gap-12">
        <div className="container space-y-4">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
              AI-powered Resume Builder
            </h1>
            <p className="max-w-[600px] mx-auto text-gray-500 md:text-xl dark:text-gray-400">
              Create a professional resume in minutes with the power of AI. Get
              past the ATS and land your dream job.
            </p>
          </div>
          <div className="mx-auto max-w-sm space-y-2 md:max-w-none md:flex md:justify-center md:space-x-2 md:space-y-0">
            <Link href="/templates">
              <Button>Get Started</Button>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
