/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QV9dJ6zcsZf
 */
import Link from "next/link"
import { JSX, SVGProps } from "react"

export function Hero() {
  return (
    <>
      <div className="bg-gray-900">
        <div className="container flex items-center justify-between h-14 px-4 mx-auto md:px-6">
          <Link className="flex items-center space-x-2 text-gray-50 hover:underline dark:text-gray-950" href="#">
            <FlagIcon className="h-6 w-6" />
            <span className="font-semibold">AI Resume</span>
          </Link>
          <nav className="hidden space-x-4 text-sm lg:flex">
            <Link
              className="flex items-center text-gray-300 hover:text-gray-50 dark:text-gray-700 dark:hover:text-gray-950"
              href="#"
            >
              Home
            </Link>
            <Link
              className="flex items-center text-gray-300 hover:text-gray-50 dark:text-gray-700 dark:hover:text-gray-950"
              href="#"
            >
              Features
            </Link>
            <Link
              className="flex items-center text-gray-300 hover:text-gray-50 dark:text-gray-700 dark:hover:text-gray-950"
              href="#"
            >
              Templates
            </Link>
            <Link
              className="flex items-center text-gray-300 hover:text-gray-50 dark:text-gray-700 dark:hover:text-gray-950"
              href="#"
            >
              Pricing
            </Link>
            <Link
              className="flex items-center text-gray-300 hover:text-gray-50 dark:text-gray-700 dark:hover:text-gray-950"
              href="#"
            >
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Link
              className="inline-flex h-10 items-center rounded-md border border-gray-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
              href="#"
            >
              Log in
            </Link>
            <Link
              className="inline-flex h-10 items-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#"
            >
              Sign up
            </Link>
          </div>
          <button className="lg:hidden">
            <MenuIcon className="w-6 h-6" />
          </button>
        </div>
      </div>
      <section className="grid items-center w-full min-h-[calc(100vh_-_nav)] py-12 gap-4 px-4 text-center md:px-6 lg:py-24 xl:gap-12">
        <div className="container space-y-4">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
              AI-powered Resume Builder
            </h1>
            <p className="max-w-[600px] mx-auto text-gray-500 md:text-xl dark:text-gray-400">
              Create a professional resume in minutes with the power of AI. Get past the ATS and land your dream job.
            </p>
          </div>
          <div className="mx-auto max-w-sm space-y-2 md:max-w-none md:flex md:justify-center md:space-x-2 md:space-y-0">
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#"
            >
              Get Started
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}


function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
