/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8TyaDV0rrgh
 */
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import TestTemplate from '@/templates/testTemplate';

export function Editor() {
  return (
    <div className="w-full max-w-90 px-4 mx-auto lg:grid lg:gap-4 lg:px-6 lg:grid-cols-2 mt-20">
      <div className="border lg:border-0 lg:rounded lg:overflow-hidden">
        <div className="p-4 space-y-4 lg:p-10">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="contact-information">Contact Information</Label>
            <Textarea
              className="min-h-[100px]"
              id="contact-information"
              placeholder="Enter your contact information"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="summary">Summary</Label>
            <Textarea
              className="min-h-[100px]"
              id="summary"
              placeholder="Enter your summary"
            />
          </div>
        </div>
        <div className="border-t">
          <div className="p-4 space-y-4 lg:p-10">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="education">Education</Label>
                <Textarea
                  className="min-h-[100px]"
                  id="education"
                  placeholder="Enter your education"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="experience">Work Experience</Label>
                <Textarea
                  className="min-h-[100px]"
                  id="experience"
                  placeholder="Enter your work experience"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="skills">Skills</Label>
                <Textarea
                  className="min-h-[100px]"
                  id="skills"
                  placeholder="Enter your skills"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <TestTemplate />
      </div>
    </div>
  );
}
