'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8TyaDV0rrgh
 */
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import React, { useEffect } from 'react';
import renderTemplate from '@/templates';
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { useEditorStore } from '@/utils/stores';
import { Button } from '@/components/ui/button';

export function Editor() {
  const setName = useEditorStore((state) => state.setName);
  const setDescription = useEditorStore((state) => state.setDescription);
  const setContact = useEditorStore((state) => state.setContact);
  const contact = useEditorStore((state) => state.contact);
  const setSkills = useEditorStore((state) => state.setSkills);
  const skills: string[] = useEditorStore((state) => state.skills);
  const [newSkill, setNewSkill] = React.useState('');

  const [template, setTemplate] = React.useState(1);
  useEffect(() => {
    const searchParams = new URLSearchParams(window.location.search);
    const templateId = searchParams.get('template');
    setTemplate(templateId ? parseInt(templateId) : 1);
  }, []);

  const downloadAsImage = async () => {
    const element = document.getElementById('resume'); // Ensure your resume template has this ID
    if (element) {
      const canvas = await html2canvas(element);
      const image = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.href = image;
      link.download = 'resume.png';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  const downloadAsPDF = async () => {
    const element = document.getElementById('resume'); // Ensure your resume template has this ID
    if (element) {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [element.offsetWidth, element.offsetHeight],
      });
      doc.html(element, {
        callback: function (doc) {
          doc.save('resume.pdf');
        },
        x: 0,
        y: 0,
        width: element.offsetWidth,
      });
    }
  };

  return (
    <div className="w-full max-w-90 px-4 mx-auto lg:grid lg:gap-4 lg:px-6 lg:grid-cols-2 mt-20">
      <div className="border lg:border-0 lg:rounded lg:overflow-hidden">
        <div className="p-4 space-y-4 lg:p-10">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input
              id="name"
              placeholder="Enter your name"
              onChange={(e) => {
                setName(e.target.value);
              }}
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="name">Address</Label>
            <Input
              id="name"
              placeholder="Enter your address"
              onChange={(e) => {
                setContact({ ...contact, address: e.target.value });
              }}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="name">Email</Label>
            <Input id="name" placeholder="Enter your address" onChange={(e) => {
              setContact({...contact, email: e.target.value});
            }} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="name">Phone</Label>
            <Input id="name" placeholder="Enter your address" onChange={(e) => {
              setContact({...contact, phone: e.target.value});
            }} />
            </div>
          <div className="space-y-2">
            <Label htmlFor="name">LinkedIn</Label>
            <Input id="name" placeholder="Enter your address" onChange={(e) => {
              setContact({...contact, linkedin: e.target.value});
            }} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="summary">Summary</Label>
            <Textarea
              className="min-h-[100px]"
              id="summary"
              placeholder="Enter your summary"
              onChange={(e) => {
                setDescription(e.target.value);
              }}
            />
          </div>
        </div>
        <div className="border-t">
          <div className="p-4 space-y-4 lg:p-10">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="education">Education</Label>
                <Textarea
                  className="min-h-[100px]"
                  id="education"
                  placeholder="Enter your education"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="experience">Work Experience</Label>
                <Textarea
                  className="min-h-[100px]"
                  id="experience"
                  placeholder="Enter your work experience"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="skills">Skills</Label>
                <Input
                  id="skills"
                  placeholder="Enter a skill"
                  onChange={(e) => {
                    setNewSkill(e.target.value);
                  }}
                  value={newSkill}
                />
                <Button
                  onClick={() => {
                    if (!newSkill) return;
                    setSkills([...skills, newSkill]);
                    setNewSkill('');
                  }}
                >
                  Add Skill
                </Button>
                <div>
                  {skills.map((skill) => (
                    <div
                      className="inline-block mr-2"
                      key={skill}
                      onClick={() =>
                        setSkills(skills.filter((s) => s !== skill))
                      }
                    >
                      {skill}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <Select
          onValueChange={(value) => {
            if (value === 'png') downloadAsImage();
            if (value === 'pdf') downloadAsPDF();
          }}
        >
          <Label>Download as :</Label>
          <SelectTrigger
            className="w-[180px] mb-3"
            style={{
              outline: 'none',
              /* Optional: Add custom styles for focus state to maintain accessibility */
              boxShadow: '0 0 0 1px rgba(0, 123, 255, 0.1)', // Example custom focus style
            }}
          >
            <SelectValue placeholder="Download" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Format</SelectLabel>
              <SelectItem value="png">PNG</SelectItem>
              <SelectItem value="pdf">PDF</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        {renderTemplate(template)}
      </div>
    </div>
  );
};
